# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servaiman.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='servaiman.proto',
  package='servaiman_proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0fservaiman.proto\x12\x0fservaiman_proto\"\x17\n\x07Request\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x1a\n\tCaimanOut\x12\r\n\x05image\x18\x01 \x03(\x05\x32O\n\tServaiman\x12\x42\n\x06GetOut\x12\x18.servaiman_proto.Request\x1a\x1a.servaiman_proto.CaimanOut\"\x00\x30\x01\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='servaiman_proto.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='servaiman_proto.Request.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=59,
)


_CAIMANOUT = _descriptor.Descriptor(
  name='CaimanOut',
  full_name='servaiman_proto.CaimanOut',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='servaiman_proto.CaimanOut.image', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['CaimanOut'] = _CAIMANOUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'servaiman_pb2'
  # @@protoc_insertion_point(class_scope:servaiman_proto.Request)
  ))
_sym_db.RegisterMessage(Request)

CaimanOut = _reflection.GeneratedProtocolMessageType('CaimanOut', (_message.Message,), dict(
  DESCRIPTOR = _CAIMANOUT,
  __module__ = 'servaiman_pb2'
  # @@protoc_insertion_point(class_scope:servaiman_proto.CaimanOut)
  ))
_sym_db.RegisterMessage(CaimanOut)



_SERVAIMAN = _descriptor.ServiceDescriptor(
  name='Servaiman',
  full_name='servaiman_proto.Servaiman',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=89,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOut',
    full_name='servaiman_proto.Servaiman.GetOut',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_CAIMANOUT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVAIMAN)

DESCRIPTOR.services_by_name['Servaiman'] = _SERVAIMAN

# @@protoc_insertion_point(module_scope)
