# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import servaiman_pb2 as servaiman__pb2


class ServaimanStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOut = channel.unary_stream(
        '/servaiman_proto.Servaiman/GetOut',
        request_serializer=servaiman__pb2.Request.SerializeToString,
        response_deserializer=servaiman__pb2.CaimanOut.FromString,
        )


class ServaimanServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOut(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServaimanServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOut': grpc.unary_stream_rpc_method_handler(
          servicer.GetOut,
          request_deserializer=servaiman__pb2.Request.FromString,
          response_serializer=servaiman__pb2.CaimanOut.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'servaiman_proto.Servaiman', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
