# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stitch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stitch.proto',
  package='stitch_proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0cstitch.proto\x12\x0cstitch_proto\"\x17\n\x07Request\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x16\n\x05Image\x12\r\n\x05image\x18\x01 \x01(\x05\x32\x42\n\x06Stitch\x12\x38\n\x08GetImage\x12\x15.stitch_proto.Request\x1a\x13.stitch_proto.Image\"\x00\x62\x06proto3')
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='stitch_proto.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='stitch_proto.Request.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=53,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='stitch_proto.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='stitch_proto.Image.image', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'stitch_pb2'
  # @@protoc_insertion_point(class_scope:stitch_proto.Request)
  ))
_sym_db.RegisterMessage(Request)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'stitch_pb2'
  # @@protoc_insertion_point(class_scope:stitch_proto.Image)
  ))
_sym_db.RegisterMessage(Image)



_STITCH = _descriptor.ServiceDescriptor(
  name='Stitch',
  full_name='stitch_proto.Stitch',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=79,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetImage',
    full_name='stitch_proto.Stitch.GetImage',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_IMAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STITCH)

DESCRIPTOR.services_by_name['Stitch'] = _STITCH

# @@protoc_insertion_point(module_scope)
