# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stitch_pb2 as stitch__pb2


class StitchStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetImage = channel.unary_unary(
        '/stitch_proto.Stitch/GetImage',
        request_serializer=stitch__pb2.Request.SerializeToString,
        response_deserializer=stitch__pb2.Image.FromString,
        )


class StitchServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StitchServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetImage': grpc.unary_unary_rpc_method_handler(
          servicer.GetImage,
          request_deserializer=stitch__pb2.Request.FromString,
          response_serializer=stitch__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stitch_proto.Stitch', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
