/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

// for each type in .proto file:
goog.provide('proto.servaiman_proto.CaimanOut');
goog.provide('proto.servaiman_proto.Request');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.servaiman_proto.Request = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.servaiman_proto.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    proto.servaiman_proto.Request.displayName = 'proto.servaiman_proto.Request';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto suitable for use in Soy templates.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
     * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
     *     for transitional soy proto support: http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.servaiman_proto.Request.prototype.toObject = function (opt_includeInstance) {
        return proto.servaiman_proto.Request.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Whether to include the JSPB
     *     instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.servaiman_proto.Request} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.servaiman_proto.Request.toObject = function (includeInstance, msg) {
        var f, obj = {
            size: jspb.Message.getFieldWithDefault(msg, 1, 0)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.servaiman_proto.Request}
 */
proto.servaiman_proto.Request.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.servaiman_proto.Request;
    return proto.servaiman_proto.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.servaiman_proto.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.servaiman_proto.Request}
 */
proto.servaiman_proto.Request.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {number} */ (reader.readInt32());
                msg.setSize(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.servaiman_proto.Request.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.servaiman_proto.Request.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.servaiman_proto.Request} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servaiman_proto.Request.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getSize();
    if (f !== 0) {
        writer.writeInt32(
            1,
            f
        );
    }
};


/**
 * optional int32 size = 1;
 * @return {number}
 */
proto.servaiman_proto.Request.prototype.getSize = function () {
    return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.servaiman_proto.Request.prototype.setSize = function (value) {
    jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.servaiman_proto.CaimanOut = function (opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, proto.servaiman_proto.CaimanOut.repeatedFields_, null);
};
goog.inherits(proto.servaiman_proto.CaimanOut, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    proto.servaiman_proto.CaimanOut.displayName = 'proto.servaiman_proto.CaimanOut';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.servaiman_proto.CaimanOut.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto suitable for use in Soy templates.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
     * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
     *     for transitional soy proto support: http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.servaiman_proto.CaimanOut.prototype.toObject = function (opt_includeInstance) {
        return proto.servaiman_proto.CaimanOut.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Whether to include the JSPB
     *     instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.servaiman_proto.CaimanOut} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.servaiman_proto.CaimanOut.toObject = function (includeInstance, msg) {
        var f, obj = {
            imageList: jspb.Message.getRepeatedField(msg, 1)
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.servaiman_proto.CaimanOut}
 */
proto.servaiman_proto.CaimanOut.deserializeBinary = function (bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.servaiman_proto.CaimanOut;
    return proto.servaiman_proto.CaimanOut.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.servaiman_proto.CaimanOut} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.servaiman_proto.CaimanOut}
 */
proto.servaiman_proto.CaimanOut.deserializeBinaryFromReader = function (msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
                msg.setImageList(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.servaiman_proto.CaimanOut.prototype.serializeBinary = function () {
    var writer = new jspb.BinaryWriter();
    proto.servaiman_proto.CaimanOut.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.servaiman_proto.CaimanOut} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.servaiman_proto.CaimanOut.serializeBinaryToWriter = function (message, writer) {
    var f = undefined;
    f = message.getImageList();
    if (f.length > 0) {
        writer.writePackedInt32(
            1,
            f
        );
    }
};


/**
 * repeated int32 image = 1;
 * @return {!Array<number>}
 */
proto.servaiman_proto.CaimanOut.prototype.getImageList = function () {
    return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<number>} value */
proto.servaiman_proto.CaimanOut.prototype.setImageList = function (value) {
    jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.servaiman_proto.CaimanOut.prototype.addImage = function (value, opt_index) {
    jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.servaiman_proto.CaimanOut.prototype.clearImageList = function () {
    this.setImageList([]);
};
